[bmscriptsbox.info]
id = "05dbedbd-b599-4bb6-93d0-103cc7e19db9"              
name = "系统静音"                                    
desc = "Windows系统静音脚本、配合不忙脚本盒子可实现快速静音和定时静音"                                  
version = "1.0.0"                                        
icon = "jingying.png"   

[bmscriptsbox.runtime]
language = "bat"  
language_version = ">=0.0.0"             
entry = "main.cmd"                   
terminal = "never"   
binaries = [{name = "nircmd"}]     

[bmscriptsbox.triggers]
[bmscriptsbox.triggers.context_menu]                   
enabled = true                                 
targets = ["background"]                        

[bmscriptsbox.triggers.shortcut]                          
enabled = true                                  

[bmscriptsbox.schedule]
enabled = true                              







